// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID    int64          `json:"id"`
	Name  string         `json:"name"`
	Phone sql.NullString `json:"phone"`
}

type Entry struct {
	ID        int64     `json:"id"`
	ProductID int64     `json:"product_id"`
	Quantity  int64     `json:"quantity"`
	CreatedAt time.Time `json:"created_at"`
}

type Order struct {
	ID          int64          `json:"id"`
	CustomerID  sql.NullInt64  `json:"customer_id"`
	TotalAmount int64          `json:"total_amount"`
	Comment     sql.NullString `json:"comment"`
	CreatedAt   time.Time      `json:"created_at"`
}

type OrderProduct struct {
	OrderID   int64 `json:"order_id"`
	ProductID int64 `json:"product_id"`
	Price     int64 `json:"price"`
	Quantity  int64 `json:"quantity"`
}

type Product struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	CostPrice    int64          `json:"cost_price"`
	SellingPrice int64          `json:"selling_price"`
	Quantity     int64          `json:"quantity"`
	Unit         string         `json:"unit"`
	Description  sql.NullString `json:"description"`
	CreatedAt    time.Time      `json:"created_at"`
}
